name: Action to send email via AWS SES without using SMTP credentials
description: Send Email via AWS SES

inputs:
  bcc:
    description: 'Email address of the BCC recipient'
    required: false
  body:
    description: 'Body of the email'
    required: false
  body_html:
    description: 'Body of the email in HTML format'
    required: false
  cc:
    description: 'Email address of the CC recipient'
    required: false
  from:
    description: 'Email address of the sender'
    required: true
  reply_to:
    description: 'Email address to reply to'
    required: false
  subject:
    description: 'Subject of the email'
    required: true
  to:
    description: 'Email address of the recipient'
    required: true

runs:
  using: node16
  main: index.js

branding:
  color: blue
  icon: mail
